### ISSUE TITLE
Below command does not work on Ubuntu

### ISSUE THREAD

**Issue by kaushal9808** [mkroli/servicemix-docker#2]
I am working with docker on Ubuntu 16.04 virtual machine env.
Provide solution for ubuntu 16.04

docker run -d -t --name servicemix -p 1099:1099 -p 8101:8101 -p 8181:8181 -p 61616:61616 -p 36888:36888 -p 44444:44444 -v /host/path/deploy:/deploy mkroli/servicemix

**Above command gives below error**
Status: Downloaded newer image for mkroli/servicemix:latest
docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/809e7ac75076f3ce29ab7a1706e4eb7b53e186971dd3abf474fae754e906a60a-init: invalid argument.

**after this i have run the below command but not able to resolve the above error**

docker rm -f $(docker ps -a -q)
docker rmi -f $(docker images -a -q)
sudo service docker stop
sudo rm -rf /var/lib/docker/aufs
sudo rm -f /var/lib/docker/linkgraph.db
sudo service docker start

 the error exact means - the daemon does not able to create aufs mount to may be lack of permission i am running ubuntu with root permission.

i have done the mount and umount also but not able to proceed

**Comment by mkroli** [comment]
To me it looks like you could be facing this issue: docker/docker#19336.
Does it also occur when you don't use the `-v` option?
